### ISSUE TITLE
Iteration Plan August 2019

### ISSUE THREAD

**Issue by Sw1ma** [Sw1ma/easycamper-apps#15]
## Summary
After successfully completing the first iteration (#3) my focus will be to extend features from the previouse iteration with more functionality and to setup some new basic features. At the end of this iteration a user should be able to navigate through some (mock) diary items, create, edit and remove (mock) items from a diary. Saving diary items to a backend won't be available yet. I'll will also setup notifications with OneSignal and handle incomming notifications. To handle opt-in/out analytics, diagnostics and auth by the user I'll setup a preference page. And for a consistent UI experience I'll setup some basic styles. A lot to do, thus great results at the end of this iteration.

### Diary
- [x] Setup a list to browse diary items #13
- [ ] Setup basic pages to add, edit and view diary items #14

### Notifications
- [x] Setup OneSignal SDK for Xamarin #16 
- [x] Require user's privacy consent #17 
- [x] Opt-in/out OneSignal SDK based on user's consent #18 
- [ ] Handle incomming push notification #19 
- [ ] Handle notifications when tapped by user #20 

### Preferences
- [x] Opt-in/out analytic services #21 
- [x] Opt-in/out dianostic services #22 
- [ ] Opt-in/out cloud-based authentication #23 

### App Info
- [x] Show information about the app #24 

### Styles
- [x] Create a basic UI style #25
