### ISSUE TITLE
Iteration Plan July 2019

### ISSUE THREAD

**Issue by Sw1ma** [Sw1ma/easycamper-apps#3]
## Summary
The main :dart: with this first iteration is to get a working proof of concept (PoC), which will consume some of the primary services of App Center and is fully navigable. I'll setup the basic app structure to navigate through pages and add some App Center services for testing purpose. To keep my focus on a working PoC, I'll be implementing the Android platform first.

### Navigation
- [x] Setup Master/Detail (hamburger) navigation #2 
- [x] Tabbed page navigation for `Lists` and `Logbook` #4 
- [x] Create ContentPages and ViewModels #5 

### App Center
- [x] Setup Continious Integration (CI) with App Center Build #6 
- [x] Setup crash reports with App Center Diagnostics #7 
- [x] Setup application insights with App Center Analytics #8 
- [x] Setup cloud-based identity with App Center Auth #9
